{% set name = "aalto-boss" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aalto-boss-{{ version }}.tar.gz
  sha256: a63713ea382c53752296904db18a8c4e5fa7bebaeeba6a51ab07e85838804ba6

build:
  entry_points:
    - boss=boss.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - scipy >=1.8
    - python >=3.7
    - numpy >=1.20
    - gpy >=1.13.1
    - matplotlib-base >=3.5

test:
  imports:
    - boss
  commands:
    - pip check
    - boss --help
  requires:
    - pip
    - cython

about:
  home: https://gitlab.com/cest-group/boss
  summary: Bayesian optimization structure search
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
