{% set name = "aalto-boss" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: be85b22f02e377a20cddcb83e461e305e592d3723fa35d11d538d39ba1aa8c90

build:
  entry_points:
    - boss=boss.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - scipy >=1.8
    - python >=3.7
    - numpy >=1.20
    - gpy >=1.13.1
    - matplotlib-base >=3.5,<3.9

test:
  imports:
    - boss
  commands:
    - pip check
    - boss --help
  requires:
    - pip
    - cython

about:
  home: https://gitlab.com/cest-group/boss
  summary: Bayesian optimization structure search
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
