{% set name = "aalto-boss" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aalto-boss-{{ version }}.tar.gz
  sha256: 3d9cc23b77ea443cd6dc2c4d22f9cb585207afcf93b148a89283d820083964ec

build:
  number: 0
  noarch: python
  entry_points:
    - boss=boss.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - gpy
    - scipy
    - numpy
    - matplotlib-base >=3.0
    - python >=3.5
    - gpy >=1.10.0
    - cython

test:
  imports:
    - boss
    - boss.bo
  commands:
    - pip check
    - boss --help
  requires:
    - pip

about:
  home: https://gitlab.com/cest-group/boss
  license: Apache-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Bayesian optimization structure search
  description: |
    Bayesian Optimization Structure Search (BOSS) is an active machine 
    learning technique for accelerated global exploration of energy and 
    property phase space. It is designed to facilitate machine learning 
    in computational and experimental natural sciences.
  doc_url: https://cest-group.gitlab.io/boss/
  dev_url: https://gitlab.com/cest-group/boss

extra:
  recipe-maintainers:
    - jan-janssen
